title: "DATA SCIENCE"
description: "CONCEPTS THROUGH QUESTIONS AND ANSWERS"
author: "Nishu Kumari Singh"
theme: jekyll-theme-cayman
baseurl: "/SELF-LEARN-ML-CONCEPTS"
url: "https://nishusingh28.github.io"
